### ISSUE TITLE
Banner size issue

### ISSUE THREAD

**Issue by JKVocalist** [JKVocalist/ExpressHolidays#2]
Only showing gray background from the banner. Not showing the map +plane which is the banner![banner](https://user-images.githubusercontent.com/9137869/44809164-f5fbca80-ab9b-11e8-9547-13ffaa63dc4f.jpg)

In CSS-
.navigation-default {
  background: #dadada url("/ExpressHolidays/images/express/banner.png") no-repeat 50% 0;
  background-size: cover;
}

In index-
  <div class="right">
      <div class="navigation-navigation-default">
        <a href="index.html"> Home</a>
        <a Href="destination1.html"> Bar Harbor </a>
        <a Href="destination2.html"> Canadian Rockies Lodge</a>
        <a Href="destination3.html"> Grand Canyon</a>
        <a Href="contact.html"> Contact Us</a>

**Comment by jeremysmithco** [comment]
@JKVocalist Can you show me the code that isn't working?

**Comment by jeremysmithco** [comment]
@JKVocalist This is how it's showing for me...
![image](https://user-images.githubusercontent.com/238215/44809865-f006e900-ab9d-11e8-9f20-3eee1a1dbf99.png)

So, I'm seeing some of the plane, but not all of it.

Your navbar is not the same dimensions as your background image, so that's part of the problem. No matter what you do, you're not going to see some part of the image.

However, you could change the background position, so that plane is closer to vertical center (chopping off the top and bottom).

```
.navigation-default {
  background: #dadada url("/ExpressHolidays/images/express/banner.png") no-repeat 50% 40%;
  background-size: cover;
}
```
I changed the `50% 0` to `50% 40%` and it looks like this:

![image](https://user-images.githubusercontent.com/238215/44809991-5c81e800-ab9e-11e8-91dd-48d1523c0795.png)

**Comment by JKVocalist** [comment]
That looks perfect! That is quite close to how I wanted it to look initially! Thank you big brother!!!<3

**Comment by jeremysmithco** [comment]
Great, you're welcome!
